# Generated by Django 3.2.9 on 2022-09-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicall', '0002_auto_20220910_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seller',
            field=models.BooleanField(null=True),
        ),
    ]
